# Use an official Nginx runtime as the base image
FROM nginx:alpine

# Copy static HTML, CSS, and JS files to the Nginx document root
COPY . /usr/share/nginx/html

# Expose port 80 to the outside world
EXPOSE 80
