pipeline {
    agent any
    
    environment {
        DOCKER_IMAGE_NAME = 'bhimkumar/css-project'
    }
    
    stages {
        stage('Checkout') {
            steps {
                // Checkout code from Git repository
                git branch: 'main', url: 'https://github.com/Bhim-Kumar/css-test-project/'
            }
        }
        
        stage('Build Docker Image') {
            steps {
                // Build Docker image
                script {
                    docker.build("${env.DOCKER_IMAGE_NAME}:${env.BUILD_NUMBER}")
                }
            }
        }
        
        stage('Run Docker Container') {
            steps {
                // Run Docker container locally
                script {
                    docker.image("${env.DOCKER_IMAGE_NAME}t:${env.BUILD_NUMBER}").run("-p 8000:80 --rm")
                }
            }
        }
    }
    
    post {
        success {
            echo 'Deployment successful! Access your application at http://localhost:8000'
        }
        failure {
            echo 'Deployment failed!'
        }
    }
}
